notifications: 
  email: 
  - michaelc@email.gwu.edu
  - lwrubel@email.gwu.edu
branches: 
  only: 
  - master
install: pip install -r requirements.txt
language: python
python: 
- "2.7"
before_install: 
- sed "s/cx_Oracle/#cx_Oracle/g" requirements.txt > test.txt
- mv test.txt requirements.txt
script: 
- cp lp/lp/local_settings.py.template lp/lp/local_settings.py
- python lp/manage.py migrate
- python lp/manage.py test lp
dist: trusty
os: linux
env: 
  matrix: 
  - DJANGO_VERSION=1.8
  global: 
  - secure: "ANeW9zzcyxIMGf2Kx5YVgDlhw24xerjhu3/v/talKPLnknECvw9dcot5FiVt8Za5OIayfpoCknkvNJTH0DStdHshVwDV4+xcZgIUOgRHVuOWOVbxIE5p8mBwyPeZNJisLxGBsjFH6MD270V5Z92uvo/vo7Y4Ro1SbY5CjuoTf7s="
  - secure: "czatX2MZFq5hdsdOEITsfYj+UbnoZmai7Kc2jyVxVRhspRKg/ta77rKS5uESkkyr+RRNqvnQHmlbo4GpaD9sAUSTo8tOBHxJtAUxG52oUtfJMIvWXbkyK5PUwoSgDvYPbrd8aqThtKj/BijvxAakfnaKwUQPpCDDU4+xLUKmTdY="
